In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [2]:
df = pd.read_csv(
    "../data/processed/online_retail_clean.csv",
    parse_dates=["InvoiceDate"]
)

df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [3]:
df["TotalAmount"] = df["Quantity"] * df["Price"]

In [4]:
reference_date = df["InvoiceDate"].max() + pd.Timedelta(days=1)

reference_date

Timestamp('2011-03-07 12:20:00')

## RFM TABLE

In [6]:
rfm = (
    df.groupby("Customer ID")
      .agg(
          Recency=("InvoiceDate",
                   lambda x: (reference_date - x.max()).days),

          Frequency=("Invoice", "nunique"),

          Monetary=("TotalAmount", "sum")
      )
      .reset_index()
)

rfm.head()

   Customer ID  Recency  Frequency  Monetary
0      12346.0       48          1  77183.60
1      12347.0       39          2   1187.18
2      12348.0       41          2   1120.24
3      12350.0       32          1    334.40
4      12352.0        5          3   1281.15

In [8]:
rfm.shape

(1766, 4)

In [9]:
rfm.info()

<class 'pandas.DataFrame'>
RangeIndex: 1766 entries, 0 to 1765
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer ID  1766 non-null   float64
 1   Recency      1766 non-null   int64
 2   Frequency    1766 non-null   int64
 3   Monetary     1766 non-null   float64
dtypes: float64(2), int64(2)
memory usage: 55.3 KB

In [12]:
rfm.describe()

        Customer ID      Recency    Frequency      Monetary
count   1766.000000  1766.000000  1766.000000   1766.000000
mean   15295.311438    40.811438     2.030578    951.388794
std     1740.279866    30.133980     2.503521   3160.154975
min    12346.000000     1.000000     1.000000      0.850000
25%    13798.250000    14.000000     1.000000    209.550000
50%    15289.000000    34.000000     1.000000    392.880000
75%    16837.250000    60.000000     2.000000    817.052500
max    18283.000000    96.000000    44.000000  77183.600000

In [13]:
rfm.head(20)

    Customer ID  Recency  Frequency  Monetary
0       12346.0       48          1  77183.60
1       12347.0       39          2   1187.18
2       12348.0       41          2   1120.24
3       12350.0       32          1    334.40
4       12352.0        5          3   1281.15
5       12356.0       48          1   2271.62
6       12359.0       27          2   2386.41
7       12361.0        9          1    189.90
8       12362.0       18          1    479.10
9       12365.0       13          2    641.38
10      12370.0       80          2   1864.27
11      12372.0       18          1    399.22
12      12373.0       33          1    364.60
13      12377.0       37          2   1628.12
14      12383.0       53          2   1251.88
15      12386.0       59          2    401.90
16      12388.0       27          2    555.35
17      12393.0       52          2    639.50
18      12395.0       24          3    911.43
19      12401.0       25          1     84.30